submitit WARNING (2022-10-02 14:24:41,677) - Bypassing signal SIGCONT
WARNING:submitit:Bypassing signal SIGCONT
INFO:submitit:Job has timed out. Ran 58 minutes out of requested 60 minutes.
submitit WARNING (2022-10-02 14:24:41,679) - Caught signal SIGUSR2 on joachims-compute-02.cs.cornell.edu: this job is timed-out.
WARNING:submitit:Caught signal SIGUSR2 on joachims-compute-02.cs.cornell.edu: this job is timed-out.
INFO:submitit:Job not requeued because: timed-out and not checkpointable.
submitit ERROR (2022-10-02 14:24:41,691) - Submitted job triggered an exception
ERROR:submitit:Submitted job triggered an exception
Traceback (most recent call last):
  File "/home/gid-cakmaks/anaconda3/envs/contextual_rs/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gid-cakmaks/anaconda3/envs/contextual_rs/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gid-cakmaks/anaconda3/envs/contextual_rs/lib/python3.8/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/home/gid-cakmaks/anaconda3/envs/contextual_rs/lib/python3.8/site-packages/submitit/core/submission.py", line 72, in submitit_main
    process_job(args.folder)
  File "/home/gid-cakmaks/anaconda3/envs/contextual_rs/lib/python3.8/site-packages/submitit/core/submission.py", line 65, in process_job
    raise error
  File "/home/gid-cakmaks/anaconda3/envs/contextual_rs/lib/python3.8/site-packages/submitit/core/submission.py", line 54, in process_job
    result = delayed.result()
  File "/home/gid-cakmaks/anaconda3/envs/contextual_rs/lib/python3.8/site-packages/submitit/core/utils.py", line 133, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "/home/gid-cakmaks/contextual_rs/experiments/wsc_experiments/main.py", line 567, in submitit_main
    output = main(
  File "/home/gid-cakmaks/contextual_rs/experiments/wsc_experiments/main.py", line 477, in main
    post_mean = model.posterior(context_map).mean.t()
  File "/home/gid-cakmaks/anaconda3/envs/contextual_rs/lib/python3.8/site-packages/botorch/models/gpytorch.py", line 600, in posterior
    tf_mvn = oct.untransform_posterior(GPyTorchPosterior(mvn)).mvn
  File "/home/gid-cakmaks/anaconda3/envs/contextual_rs/lib/python3.8/site-packages/botorch/models/transforms/outcome.py", line 368, in untransform_posterior
    mean_tf = offset.squeeze(-1) + scale_fac.squeeze(-1) * mvn.mean
  File "/home/gid-cakmaks/anaconda3/envs/contextual_rs/lib/python3.8/site-packages/submitit/core/job_environment.py", line 226, in checkpoint_and_try_requeue
    raise utils.UncompletedJobError(message)
submitit.core.utils.UncompletedJobError: Job not requeued because: timed-out and not checkpointable.
srun: error: joachims-compute-02: task 0: Exited with exit code 1
